### ISSUE TITLE
🔥  Roadmap

### ISSUE THREAD

**Issue by aggmoulik** [redwoodjs/made-by-redwood#1]
Inspired by the Made with Supabase Project, we have thought to have our own made-with-redwood website, where people can show off their projects made with [RedwoodJS](https://redwoodjs.com/).

💡 Feature Request
- [ ] Custom Profile for a User
- [ ] Analytics for the website ( Decide what to choose )
     - [Open Source Analytics - Umami ](https://umami.is/)
     - [Plausible Analytics](https://plausible.io/)
- [ ] Weekly/Monthly Trending Projects
- [ ] Custom Community Redwood Points
     - It can help us in finding the highlight of the community ( weekly / monthly ), according to the contribution. We will surely use it for more amazing things.

Well, we are an open-source community, feel free to open an issue in the project for any more feature requests or [discussions](https://community.redwoodjs.com/).

**Comment by aggmoulik** [comment]
Hey @thedavidprice @barakcodes @KrisCoulson, Would love to get your views on any more important features.

I have created a basic example [here](https://github.com/aggmoulik/redwood-showcase). It needs a lot of work but surely we will reach to the best community project ever.
